/run UIErrorsFrame:Clear();
/run if not UnitBuff("player","Слово Силы: Стойкость") then CastSpellByName("Слово Силы: Стойкость") end;
/run UIErrorsFrame:Clear();
/run if not UnitBuff("player","Внутренний огонь") then CastSpellByName("Внутренний огонь") end;
/run UIErrorsFrame:Clear();
/run if not UnitDebuff("target","Слово Тьмы: Боль") then CastSpellByName("Слово Тьмы: Боль") end;
/run UIErrorsFrame:Clear();
/run if GetSpellCooldown("Взрыв разума")==0 then CastSpellByName("Взрыв разума") end;
/run UIErrorsFrame:Clear();
/run if UnitDebuff("target","Слово Тьмы: Боль") then CastSpellByName("Кара") end;
/run UIErrorsFrame:Clear();
